french_words = [
    {"french": "le", "english": "the"},
    {"french": "de", "english": "of"},
    {"french": "un", "english": "a"},
    {"french": "à", "english": "to"},
    {"french": "être", "english": "be"},
    {"french": "et", "english": "and"},
    {"french": "encore", "english": "again"},
    {"french": "moins", "english": "minus"},
    {"french": "sans", "english": "without"},
    {"french": "faire", "english": "make"},
    {"french": "part", "english": "part"},
    {"french": "deux", "english": "two"},
    {"french": "avant", "english": "before"},
    {"french": "trois", "english": "three"},
    {"french": "nous", "english": "we"},
    {"french": "où", "english": "where"},
    {"french": "bien", "english": "well"},
]